### ISSUE TITLE
Add API or documentation for dealing with CBOR Sequences

### ISSUE THREAD

**Issue by aaronhuggins** [aaronhuggins/cbor-redux#19]
Technically, the encoder/decoder are handling all well-formed CBOR byte sequences. However, sequences of well-formed CBOR result in an error.

```TypeScript
function hex2arrayBuffer(data: string) {
  const length = data.length / 2;
  const ret = new Uint8Array(length);

  for (let i = 0; i < length; i += 1) {
    ret[i] = parseInt(data.substr(i * 2, 2), 16);
  }

  return ret.buffer;
}

decode(hex2arrayBuffer('a201020304a202010405'))
```

The above code results in this error:
```
error: Uncaught Error: CBORError: Remaining bytes
  if (offset !== data.byteLength) throw new Error("CBORError: Remaining bytes");
                                        ^
    at decode (file:///media/user/development/cbor-redux/src/decode.ts:291:41)
    at file:///media/user/development/cbor-redux/example.ts:14:1
```

CBOR sequences should be serializable and de-serializable.

**Comment by aaronhuggins** [comment]
Added simple API to iterate over remaining CBOR bytes and decode them into a `Sequence` class when decoding in `mode: "sequence". This mode carries over the default strictness requirement, as CBOR sequences MUST only have well-formed CBOR values.

The `encode` API may take this `Sequence` class as an input and create a valid CBOR sequence. Nested `Sequence` classes will cause an error, as nesting a CBOR sequence **will** produce an invalid CBOR value or an unexpected "insert" of sequence data in a CBOR sequence.
